Add: sorted of title, compare password in registration
kopo4eweb/test-guru pull request #15
Opened 2020-12-29 17:17 UTC by kopo4eweb

2021-01-10 07:32 UTC, BubuntuClu requested changes

2021-01-10 07:32 UTC, BubuntuClu commented on app/assets/javascripts/utilities/registration.js
> +  } else if (pwdCmf == '') {
зачем тут else if?

2021-01-10 07:32 UTC, BubuntuClu commented on app/assets/javascripts/utilities/registration.js
> +  if (pwdCmf != '' && pwd != pwdCmf) {
не очень хороший код получился. разбей его на if+return когда пароль какой-то пустой и на просто if/else когда что-то ввели

2021-01-11 08:40 UTC, kopo4eweb commented on app/assets/javascripts/utilities/registration.js
> +  } else if (pwdCmf == '') {
уже и не вспомню.... :(

2021-01-11 17:25 UTC, merged