Test timer
kopo4eweb/test-guru pull request #19
Opened 2021-01-26 16:26 UTC by kopo4eweb

2021-01-26 19:08 UTC, BubuntuClu requested changes

2021-01-26 19:08 UTC, BubuntuClu commented on app/assets/javascripts/utilities/countdown.js
> +      window.location.href = '/test_passages/'+ testPassageId +'/result'
я думаю что лучше забмитить форму. вдруг человек выбрал вариант ответа, но не успел нажать. в твоем случае ответ не будет проверяться

2021-01-26 19:08 UTC, BubuntuClu commented on app/models/test_passage.rb
> +    return 0 if time_left_seconds < 0
тест без таймера уже не получится сделать?

2021-01-27 08:30 UTC, kopo4eweb commented on app/assets/javascripts/utilities/countdown.js
> +      window.location.href = '/test_passages/'+ testPassageId +'/result'
В условии задачи сказано: "При истечении времени таймера тест считается не пройденным.", поэтому сделал так, что если не успел в отведенное время, он все равно тест не стал. 
Хотя по мне, если не успел ответить на сотый вопрос, но до этого на 99 ответил, лишать награды, только по тому что не успел в условное время, не правильно! Поэтому сделаю как ты написал.

2021-01-27 09:54 UTC, kopo4eweb commented on app/models/test_passage.rb
> +    return 0 if time_left_seconds < 0
Спасибо! Когда делал эту штуку "При истечении времени таймера тест считается не пройденным." сломал и забыл проверить!

2021-01-27 19:01 UTC, BubuntuClu approved these changes

2021-01-27 19:01 UTC, BubuntuClu commented on app/controllers/test_passages_controller.rb
> +    elsif @test_passage.time_is_over?
воу-воу, а почему бы просто не сделать `if @test_passage.completed? || @test_passage.time_is_over?`? 
тогда не будет этого кривого `elsif`.

2021-01-27 19:08 UTC, kopo4eweb commented on app/controllers/test_passages_controller.rb
> +    elsif @test_passage.time_is_over?
Действительно! Спасибо!

2021-01-27 19:19 UTC, merged