Lesson 4
kopo4eweb/test-guru pull request #4
Opened 2020-12-07 18:43 UTC by kopo4eweb

2020-12-07 20:19 UTC, BubuntuClu requested changes

2020-12-07 20:19 UTC, BubuntuClu commented on app/models/test.rb
> +      .where('categories.title = ?', category)
а сортировка и выборка где?

2020-12-07 20:19 UTC, BubuntuClu commented on app/models/test.rb
> +    Test.joins('JOIN categories ON tests.category_id = categories.id')
имея ассоциацию с категориями, ты можешь заменить на `joins(:category)`

2020-12-07 20:19 UTC, BubuntuClu commented on db/migrate/20201207164217_add_field_title_to_answer.rb
> +    change_column_null :answers, :title, false
почему эту опцию не задаешь сразу при добавление колонки? зачем отдельная строка для этого?

2020-12-08 06:57 UTC, kopo4eweb commented on db/migrate/20201207164217_add_field_title_to_answer.rb
> +    change_column_null :answers, :title, false
`add_column :answers, :title, :string, null: false`
так происходит ошибка при выполнении миграции
SQLite3::SQLException: Cannot add a NOT NULL column with default value NULL: ALTER TABLE "answers" ADD "title" varchar NOT NULL

2020-12-08 07:25 UTC, kopo4eweb commented on app/models/test.rb
> +    Test.joins('JOIN categories ON tests.category_id = categories.id')
Читал на форуме, так как еще не проходили ассоциации, то надо писать join запросом. Хотя, я за то что использовать встроенные механизмы AR.

Переписал.

2020-12-08 07:25 UTC, kopo4eweb commented on app/models/test.rb
> +      .where('categories.title = ?', category)
Извеняюсь, пропустил.

2020-12-08 07:32 UTC, BubuntuClu commented on db/migrate/20201207164217_add_field_title_to_answer.rb
> +    change_column_null :answers, :title, false
аа, это классный SQLite, понятно

2020-12-08 07:36 UTC, BubuntuClu requested changes

2020-12-08 07:36 UTC, BubuntuClu commented on app/models/test.rb
> +    title_tests = []
не, есть более простой способ. без создания пустого массива

2020-12-08 07:36 UTC, BubuntuClu commented on app/models/test.rb
> +      .each { |test| title_tests << test.title }
замени на метод `pluck` это вернет массив выбранных тобой полей


это не надо использовать тут, но просто совет, если нужно вернуть массив, то это сделать проще через `map`
`.map { |test| test.title }` - map возвращает массив

2020-12-08 07:36 UTC, BubuntuClu commented on app/models/test.rb
> +    title_tests = []
ниже отписал

2020-12-08 08:08 UTC, kopo4eweb commented on app/models/test.rb
> +      .each { |test| title_tests << test.title }
Да, точно, упустил из виду этот метод, тут даже примеры его использования были и что им можно заменить http://rusrails.ru/active-record-query-interface#pluck а не городить решение с масивами.
Про map забыл, не так часто его использовал. Спасибо!

2020-12-08 10:14 UTC, merged