Add: views
kopo4eweb/test-guru pull request #8
Opened 2020-12-14 09:13 UTC by kopo4eweb

2020-12-14 18:48 UTC, BubuntuClu requested changes

2020-12-14 18:48 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +  before_action :find_test
тест тебе не во всех экшенах нужен, и у тебя shallow опция включена, у тебя даже ошибки будут падать

2020-12-14 18:48 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +  before_action :find_question, except: [:index, :create]
какой вопрос у тебя ищется в index методе? и в create? может ты напутал чего-то?

2020-12-14 18:48 UTC, BubuntuClu commented on app/helpers/application_helper.rb
> +    "<a href='https://github.com/#{author}/#{repo}' target='_blank'>#{repo}</a>".html_safe
можно возвращать хэлпер `link_to` вместо куска html

2020-12-14 18:48 UTC, BubuntuClu commented on app/helpers/questions_helper.rb
> +  def question_header
передавай сюда явно объект вопроса и проверяй существует ли он в БД или нет

2020-12-15 11:15 UTC, kopo4eweb commented on app/controllers/questions_controller.rb
> +  before_action :find_question, except: [:index, :create]
наоборот, так я исключаю срабатываение поиска вопроса при вызовах этих методов, или лучше для этих целей использовать такую конструкцию?
`skip_before_action :find_question, only: [:index, :create]`

2020-12-15 11:53 UTC, kopo4eweb commented on app/controllers/questions_controller.rb
> +  before_action :find_test
ошибки падали, но я их усключил проверкой существования параметра 
```
  def find_test
    @test = Test.find(params[:test_id]) **if params[:test_id]**
  end
```
видимо это не правильный вариант, поэтому переписал, указав в для каких методов оно должно срабатывать

2020-12-15 19:24 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +  before_action :find_question, except: [:index, :create]
а, мой косяк, да. не обратил внимания на except. твой изначальный вариант подходит

2020-12-15 19:25 UTC, BubuntuClu approved these changes

2020-12-15 19:25 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +  before_action :find_question, only: [:edit, :show, :update, :destroy]
my bad

2020-12-16 12:31 UTC, merged