Logic
kopo4eweb/test-guru pull request #9
Opened 2020-12-18 07:35 UTC by kopo4eweb

2020-12-18 15:39 UTC, BubuntuClu requested changes

2020-12-18 15:39 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +    @test = Test.new(test_params)
у тебя есть ассоциация созданных тестов. надо ее тут использовать. чтобы не было костыля ниже

2020-12-18 15:39 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +    @test.author = User.last
у тебя ведь есть метод который находит пользователя, используй его, не надо код дублировать

2020-12-18 15:39 UTC, BubuntuClu commented on app/views/test_passages/result.html.erb
> +<% if @test_passage.percent_success_answer >= 85 %>
что такое 85? без контекста это просто магическое число. надо убрать его в модель и обозвать понятно.
так же само это сравнение можно поместить в метод `success?`

2020-12-18 15:43 UTC, BubuntuClu requested changes

2020-12-18 15:43 UTC, BubuntuClu commented on db/migrate/20201218110715_add_field_to_test_passages.rb
> +    add_column :test_passages, :passed_questions, :integer
это избыточно поле. у тебя есть все чтобы посчитать номер текущего вопроса

2020-12-18 15:43 UTC, BubuntuClu commented on db/migrate/20201217174102_drop_table_tests_users.rb
> +  def up
если есть `up` то должен быть `down`

2020-12-18 16:00 UTC, kopo4eweb commented on db/migrate/20201218110715_add_field_to_test_passages.rb
> +    add_column :test_passages, :passed_questions, :integer
я не придумал варианта, как обойтись без этого поля :(

2020-12-18 16:54 UTC, kopo4eweb commented on db/migrate/20201218110715_add_field_to_test_passages.rb
> +    add_column :test_passages, :passed_questions, :integer
вроде придумал, правда не знаю на сколько оно правильное

2020-12-18 19:38 UTC, BubuntuClu approved these changes

2020-12-18 19:38 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +    @test.author = @user
Ассоциацию используй. То что ты заменил это ты молодец, но костыль то остался

2020-12-18 19:38 UTC, BubuntuClu commented on db/migrate/20201217174102_drop_table_tests_users.rb
> +    create_table :tests_users do |t|
Можно было пустой оставить. У тебя в up проверка на существование, не упадет если нет таблицы

2020-12-19 11:01 UTC, kopo4eweb commented on app/controllers/tests_controller.rb
> +    @test.author = @user
я могу сдедать так:
```
@test = @user.tests.new(test_params)    
@test.author = @user
```
но без явного указания автора, тест нельзя создать.

Покажи, пожалуйста, как правильно нужно сделать.

2020-12-19 11:19 UTC, kopo4eweb commented on app/controllers/tests_controller.rb
> +    @test.author = @user
сам дошел до решения

2020-12-19 14:47 UTC, merged